name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build configure
      run: g++ --std=c++20 ./configure.cc -o configure
    - name: configure
      run:  ./configure
    - name: ninja
      run: ninja
